/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xun_sodalibrary_utils_Ccc */

#ifndef _Included_com_xun_sodalibrary_utils_Ccc
#define _Included_com_xun_sodalibrary_utils_Ccc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xun_sodalibrary_utils_Ccc
 * Method:    cdf
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xun_sodalibrary_utils_Ccc_cdf
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
